"""Lua bytecode loader and VM entry point."""
from __future__ import annotations

from binary.io import Reader
from binary.reader import read_header, read_proto
from binary.header import Header
from structs.function import Proto
from parser.lexer import Lexer
from parser.block import Parser
# from vm.state import LuaState

# TODO
import sys
from pathlib import Path

# 将项目根目录加入 Python 路径
project_root = Path(__file__).parent
sys.path.insert(0, str(project_root))


class PyLua:
    reader: Reader
    header: Header
    main: Proto

    def __init__(self, file_path: str):
        with open(file_path, 'rb') as f:
            self.reader = Reader(f)
            self.header = read_header(self.reader)
            self.main = read_proto(self.reader)

    def __str__(self) -> str:
        return f"{self.main}"


if __name__ == "__main__":
    # Test with test2.lua
    print("=== Testing test2.lua (simple function) ===\n")
    # pylua_file = PyLua("test2.luac")
    # state = LuaState(pylua_file.main)

    lexer = Lexer.from_file("test2.lua")
    parser = Parser.from_lexer(lexer)

    info = parser.to_info()
    proto = info.to_proto()

    print("Generated Bytecode:")
    print(info)
