"""Lua bytecode loader and VM entry point."""
from __future__ import annotations

from lua_io import Reader
from lua_bin import read_header, read_proto
from lua_header import Header
from lua_function import Proto
from lua_state import LuaState
from lua_operator import Operator
from parser.lua_lexer import Lexer
from parser.lua_block import Chunk

# TODO
import sys
from pathlib import Path

# 将项目根目录加入 Python 路径
project_root = Path(__file__).parent
sys.path.insert(0, str(project_root))


class LuaVM:
    @staticmethod
    def fetch(state: LuaState):
        return state.fetch()

    @staticmethod
    def excute(state: LuaState) -> bool:
        inst = LuaVM.fetch(state)
        if inst is None:
            return False
        op_name = inst.op_name()
        method = getattr(Operator, op_name, None)
        if method:
            # print(f"-{len(state.call_info)}- " +  str(inst).ljust(40))
            method(inst, state)
            # print(f"-{len(state.call_info)}- " +  ''.join(f"[{v}]" for v in state.stack))
        return True

    @staticmethod
    def get_rk(state: LuaState, rk: int):
        return state._get_rk(rk)


class PyLua:
    reader: Reader
    header: Header
    main: Proto

    def __init__(self, file_path: str):
        with open(file_path, 'rb') as f:
            self.reader = Reader(f)
            self.header = read_header(self.reader)
            self.main = read_proto(self.reader)

    def __str__(self) -> str:
        return f"{self.main}"


if __name__ == "__main__":
    # Test with test2.lua
    print("=== Testing test2.lua (simple function) ===\n")
    # pylua_file = PyLua("test2.luac")
    # state = LuaState(pylua_file.main)

    lexer = Lexer.from_file("test2.lua")
    chunk = Chunk.parse(lexer)
    
    info = chunk.to_info()
    proto = info.to_proto()
    
    print("Generated Bytecode:")
    print(info)

